### PR TITLE
Generalised messages and added Macmini to possible model identifiers

### PR DESCRIPTION
**Pull request by Kuchiru**
I generalised the messages and added support for Macmini's as they can have fusion drives too, please review the changes and merge if you deem them 'worthy' :)

Regards & thanks for the amazing script!

### CODE REVIEW

**Comment by erikng** [comment]
Looks good but there is a space on line 71 that wasn't there before. Is that an accident?

**Comment by erikng** [comment]
Sorry, line 70.

**Comment by Kuchiru** [comment]
Hm, i didn't actually touch the end of the file, i removed it now.

By the way, have you considered using 'sysctl hw.model' instead of system_profiler ? 
There would be no need to have it work trough the XML, even though it's very quick already.

There is a variable that DS sets by itself that should pick up the hardware model as well, but i don't have experience with the reliability of it.

**Comment by erikng** [comment]
I'll play around with it, but I may not have time to do it. 

As for the variables, my GitHub versions are written with DeployStudio in mind, but ideally I want these scripts to work with Imagr as well. 

I'll merge this soon.

**Comment by erikng** [comment]
Hey the extra space on line 70 is still there.

**Comment by Kuchiru** [comment]
Lmao, I must be going crazy because definitely removed it, could it be github doing this ?
Also, when i edit it's not there..

**Comment by erikng** [comment]
What editor are you using? TextWrangler does some odd things.

**Comment by Kuchiru** [comment]
I actually use Sublime Text 2, but when i use the web editing its not there either.

**Comment by erikng** [comment]
Okay I figured it out and I should have paid a little more attention. I manually made the commit and thanked you. 

Thanks for the feedback - I like the change.

**Pull request closed without merging**
